# Generated by Django 2.2 on 2019-05-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZhiwangEngineer',
            fields=[
                ('titleid', models.CharField(db_column='titleID', max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('mentor', models.CharField(blank=True, max_length=255, null=True)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('graduate_data', models.CharField(blank=True, max_length=255, null=True)),
                ('key_word', models.CharField(blank=True, max_length=255, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('cited', models.IntegerField(blank=True, null=True)),
                ('download', models.IntegerField(blank=True, null=True)),
                ('paper_url', models.CharField(blank=True, max_length=255, null=True)),
                ('cite_periodical', models.TextField(blank=True, null=True)),
                ('cite_master', models.TextField(blank=True, null=True)),
                ('cite_doctor', models.TextField(blank=True, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'zhiwang_engineer',
                'managed': False,
            },
        ),
    ]
